### PR TITLE
Add ability to override apiserver's init container resources requests and limits

### LINKED ISSUE #231: (K8s) Override apiserver's init container resource request and limits
**Is your feature request related to a problem? Please describe.**

As of now there are no way to override init container resources limits for the apiserver, this could be slightly tedious to deal with if a cluster have admission controller that requires all pod to specify resource limits.

**Describe the solution you'd like**

Being able to override or patch apiserver's initContainer resource limits declaratively by updating the existing helm chart

Something like this would be great `values.yaml`
```yaml
apiserver:
   initContainer:
      resources:
          requests: {}
          limits: {}
```

**Describe alternatives you've considered**

Editing live manifest(tedious)

### PR DESCRIPTION
**Pull request by Hannarong98**
## Description

Hi, I am not super familiar with helm charts but I had tested the changes I had made and it seems to work.

Note that I did not change the chart version as I dont know if that its safe to change, I can bump it up so let me know 😄 

Closes #231 

## Type of change

- [x] (Might be a breaking change) New feature
- [x] This change requires a documentation update

## How Has This Been Tested?

I had deployed the application with helm install on my kind cluster locally (with update values file)

`values.yaml`
image

https://github.com/fonoster/routr/assets/42358864/4b980b6c-e9ad-4c37-8388-9d8ce8165c32

https://github.com/fonoster/routr/assets/42358864/1ff5d224-85cf-4288-a7bb-6f73d2bd5701

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by psanders** [comment]
Let’s try to bring this home. As we evaluate our Helm configurations, I've noticed that we have a few properties floating around. Specifically, properties like migrationsEnabled and migrationsImage aren’t tied to a central theme or section. By introducing the initContainers section, we’re potentially adding another isolated property to the mix.

Given this, I’ve considered two structured approaches:

**Idea 1:** Centralize everything under a unified migrations section:

```yaml
migrations:
  enabled: true
  image:
    # APIServer image repository
    repository: fonoster/routr-pgdata
    # APIServer image tag (immutable tags are recommended)
    # Uncomment to overwrite Chart.appVersion
    # tag: latest
    # APIServer image pull policy default to IfNotPresent
    pullPolicy: IfNotPresent
  # Resource limits and requests
  resources:
    # Resource limits
    limits: {}
    # Resource requests
    requests: {}
```

Idea #2: Incorporate migrations as a part of initContainers:

```yaml
initContainers:
  migrations:
    enabled: true
    image:
      # APIServer image repository
      repository: fonoster/routr-pgdata
      # APIServer image tag (immutable tags are recommended)
      # Uncomment to overwrite Chart.appVersion
      # tag: latest
      # APIServer image pull policy default to IfNotPresent
      pullPolicy: IfNotPresent
    # Resource limits and requests
    resources:
      # Resource limits
      limits: {}
      # Resource requests
      requests: {}
```

Any thoughts? I'm open to considering other ideas to achieve this.

**Comment by Hannarong98** [comment]
Hmmm, I really prefer the first option as its the more simple and generic solution of the two. I can update the PR, if you otherwise comes up with another idea.

**Comment by psanders** [comment]
Sounds good. Also, could you please add defaults to the values.yaml? This would be similar to the ones above, and it would help minimize the required values.

**Comment by Hannarong98** [comment]
Yes I can do that

**Comment by Hannarong98** [comment]
I think I've changed all that we needed, here is a screencap of resources requests and limits.

(default)
image


(non-default)
image

**Review by psanders — APPROVED** [review]
All good here!

**Comment by psanders** [comment]
@Hannarong98 This is a great improvement. Huge thanks for the contribution.

**Pull request merged**
