### PR TITLE
feat: add support for Remote Cloud Development with Gitpod

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
This PR would help contributors to skip all the manual installation work and they would directly redirected to ready to code environment. And they can even contribute on their browser or from any device.

## About this PR

It contains `.gitpod.yml` file, it currently configured to use it from `v2` branch. 

Test it out:

[Open in Gitpod](https://gitpod.io/#https://github.com/gitpod-forks/fonoster-routr)

<a href="https://gitpod.io/#https://github.com/fonoster/routr/pull/134"></a>

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
Maybe this is the issue, because you clicked on the PR link ( I think it may fail because of change in branch).

But this should work: 

[Open in Gitpod](https://gitpod.io/#https://github.com/gitpod-forks/fonoster-routr)

**Comment by psanders** [comment]
Please watch my comments in the video below:

https://www.loom.com/share/36a79d1b38334a5787b676c707a023c0

**Comment by psanders** [comment]
@Siddhant-K-code

Great news. 

We found that the problem had nothing to do with Gitpod but a lousy configuration file. I'm merging the PR.

Thanks a lot for your contribution.

**Comment by Siddhant-K-code** [comment]
hey, @psanders thanks for debugging that 🙌🏼 

I have resolved the file conflicts, now we are good to go 🚀

**Pull request merged**
